# configs/model_cfg/unetplusplus/unetplusplus_efficientnetv2-m.yaml

model:
  arch: "UnetPlusPlus"
  encoder_name: "tu-efficientnetv2_rw_m"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 29

metadata:
  description: "EfficientNetv2 기반의 UnetPlusPlus 모델"
  image_size: "2048x2048"
  batch_size: "1"
  version: "1.0"
  author: "andantecode"
  date: "2024-11-23"

