# configs/data_cfg/2048x2048.yaml

# notes: If you want to increase the learning resolution, \
#      : you must also adjust the resize of the augmentation.

data:
  train_data_path: /data/ephemeral/data/train/DCM
  train_label_path: /data/ephemeral/data/train/outputs_json
  test_data_path: /data/ephemeral/data/test/DCM
  # meta_data_path: /data/ephemeral/data/metadata.json # If you don’t use metadata, remove this line. (feat. experiments configs file)
  pin_memory: true
  train:
    batch_size: 1
    num_workers: 1
    shuffle: true
  val:
    batch_size: 1
    num_workers: 1
    shuffle: false
  test:
    batch_size: 1
    num_workers: 1
    shuffle: false
  predict:
    batch_size: 1
    num_workers: 1
    shuffle: false

# 동적으로 처리할 수 있다면 더 좋을 이미지 크기 설정
# 기본적으로 validation, test resize 크기
image_size: 2048
val_fold: 0  # 교차 검증에서 사용될 fold 수
seed: 21  # 랜덤 시드 값