# configs/loss_cfg/combined/dice_bce.yaml

loss:
  use_different_loss: True
  components:
    - name: DiceLoss
      args:
        mode: multilabel
        smooth: 0.0001
      weight: 0.5
    - name: FocalLoss
      args:
        mode: multilabel
        alpha: 0.25
      weight: 0.5